2. Execute the experiment 4 using sql join.

SELECT DISTINCT D.DEPTNO, D.DNAME, D.LOC
FROM DEPT D
INNER JOIN EMP E ON D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO, D.DNAME, D.LOC
HAVING COUNT(E.EMPNO) >= 2;
