1.	List the Deptno where there are no emps. 
  
SELECT DEPTNO
FROM DEPT
WHERE DEPTNO NOT IN (SELECT DISTINCT DEPTNO FROM EMP);


(2.) CREATE TABLE DEPT (
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);


(3.) SELECT * 
FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'BLAKE');
