2.	Entering data in CLIENT_MASTER


INSERT ALL
INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C00001', 'Ivan
Bayross', 'Mumbai', 400054, 'Maharashtra', 15000)
INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C00002', 'Mamta
Muzumdar', 'Madras', 780001, 'Tamil Nadu', 0)
INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C00003', 'Chhaya
Bankar', 'Mumbai', 400057, 'Maharashtra', 5000)
INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C00004', 'Ashwini
Joshi', 'Bangalore', 560001, 'Karnataka', 0)
INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C00005', 'Hansel
Colaco', 'Mumbai', 400060, 'Maharashtra', 2000)
INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C00006', 'Deepak
Sharma', 'Mangalore', 560050, 'Karnataka', 0) SELECT * FROM dual;
