b)	Entering data in PRODUCT_MASTER 
INSERT ALL
INTO PRODUCT_MASTER (PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNIT_MEASURE, QTYONHAND, REORDER_LVL, SELLPRICE, COSTPRICE) VALUES ('P00001', 'T-Shirt', 5, 'Piece', 200, 50, 350, 250)
INTO PRODUCT_MASTER (PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNIT_MEASURE, QTYONHAND, REORDER_LVL, SELLPRICE, COSTPRICE) VALUES ('P0345', 'Shirts', 6, 'Piece', 150, 50, 500, 350)
INTO PRODUCT_MASTER (PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNIT_MEASURE, QTYONHAND, REORDER_LVL, SELLPRICE, COSTPRICE) VALUES ('P06734', 'Cotton jeans', 5, 'Piece', 100, 20, 600, 450)
INTO PRODUCT_MASTER (PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNIT_MEASURE, QTYONHAND, REORDER_LVL, SELLPRICE, COSTPRICE) VALUES ('P07865', 'Jeans', 5, 'Piece', 100, 20, 750, 500)
INTO PRODUCT_MASTER (PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNIT_MEASURE, QTYONHAND, REORDER_LVL, SELLPRICE, COSTPRICE) VALUES ('P07868', 'Trousers', 2, 'Piece', 150, 50, 850, 550)
INTO PRODUCT_MASTER (PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNIT_MEASURE, QTYONHAND, REORDER_LVL, SELLPRICE, COSTPRICE) VALUES ('P07885', 'Pull Overs', 2.5, 'Piece', 80, 30, 700, 450)
INTO PRODUCT_MASTER (PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNIT_MEASURE, QTYONHAND, REORDER_LVL, SELLPRICE, COSTPRICE) VALUES ('P07965', 'Denim jeans', 4, 'Piece', 100, 40, 350, 250)
INTO PRODUCT_MASTER (PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNIT_MEASURE, QTYONHAND, REORDER_LVL, SELLPRICE, COSTPRICE) VALUES ('P07975', 'Lycra tops', 5, 'Piece', 70, 30, 300, 175)
INTO PRODUCT_MASTER (PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNIT_MEASURE, QTYONHAND, REORDER_LVL, SELLPRICE, COSTPRICE) VALUES ('P08865', 'Skirts', 5, 'Piece', 75, 30, 450, 300)
SELECT * FROM dual;
