	

INSERT ALL
INTO SALESMAN_MASTER (SALESMANNO, SALESMANNAME, ADDRESS1, ADDRESS2, CITY, PINCODE,
STATE) VALUES ('S00001', 'Aman', 'A/14','Worli', 'Mumbai', 400002, 'Maharashtra')
INTO SALESMAN_MASTER (SALESMANNO, SALESMANNAME, ADDRESS1, ADDRESS2, CITY, PINCODE,
STATE) VALUES ('S00002', 'Omkar', '65 ','Nariman', 'Mumbai', 400001, 'Maharashtra')
INTO SALESMAN_MASTER (SALESMANNO, SALESMANNAME, ADDRESS1, ADDRESS2, CITY, PINCODE,
STATE) VALUES ('S00003', 'Raj', 'P-7 ','Bandra', 'Mumbai', 400032, 'Maharashtra')
INTO SALESMAN_MASTER (SALESMANNO, SALESMANNAME, ADDRESS1, ADDRESS2, CITY, PINCODE,
STATE) VALUES ('S00004', 'Ashish', 'A/5 ','Juhu', 'Mumbai', 400044, 'Maharashtra') SELECT * FROM dual;
