Table Name: PRODUCT_MASTER 
Description:    used to store product information
CREATE TABLE PRODUCT_MASTER ( PRODUCTNO VARCHAR(6), DESCRIPTION VARCHAR(15), PROFITPERCENT DECIMAL(4,2), UNIT_MEASURE VARCHAR(10), QTYONHAND INTEGER, REORDER_LVL INTEGER, SELLPRICE DECIMAL(8,2), COSTPRICE DECIMAL(8,2)
);
