
CREATE TABLE SALESMAN_MASTER ( SALESMANNO VARCHAR(6), SALESMANNAME VARCHAR(20), ADDRESS1 VARCHAR(30), ADDRESS2 VARCHAR(30),
CITY VARCHAR(20),
 
PINCODE INTEGER, STATE VARCHAR(20), SALAMT REAL,
TGTTOGET DECIMAL(10,2), YTDSALES NUMBER(6,2), REMARKS VARCHAR(60)
);
