(1.) CREATE TABLE EMP (
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);

SELECT * 
FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'BLAKE');


SELECT * 
FROM EMP 
WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');

