(1.) CREATE TABLE EMP (
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);

SELECT * 
FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'BLAKE');


SELECT * 
FROM EMP 
WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');

SELECT * 
FROM EMP 
WHERE SAL IN (SELECT SAL FROM EMP WHERE ENAME IN ('FORD', 'SMITH'))
ORDER BY ENAME DESC;


SELECT * 
FROM EMP 
WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'MILLER')
OR SAL > (SELECT SAL FROM EMP WHERE ENAME = 'ALLEN');


SELECT * 
FROM EMP 
WHERE SAL = (SELECT MAX(SAL) FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES'));


SELECT *
FROM EMP
WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING'));


SELECT ENAME
FROM EMP E1
WHERE SAL = (SELECT MAX(SAL) FROM EMP E2 WHERE E1.DEPTNO = E2.DEPTNO);


SELECT *
FROM EMP
WHERE SAL = (SELECT (MAX(SAL) + MIN(SAL)) / 2 FROM EMP);


SELECT *
FROM EMP
WHERE HIREDATE IN (SELECT HIREDATE FROM EMP GROUP BY HIREDATE HAVING COUNT(*) > 1);


SELECT E.*
FROM EMP E
JOIN EMP M ON E.MGR = M.EMPNO
WHERE E.HIREDATE < M.HIREDATE;


